export const chartConfigs = [
  {
    type: "TCU",
    title: "Throttle Control Unit",
    fields: [
      { key: "apps1", label: "APPS 1", color: "#4CAF50" },
      { key: "apps2", label: "APPS 2", color: "#F44336" },
      { key: "bse", label: "Brake Sensor", color: "#2196F3" },
      { key: "status", label: "Status", color: "#FFC107" },
    ],
    colors: ["#4CAF50", "#F44336", "#2196F3", "#FFC107"],
    unit: "V",
    dashboard: true,
    historicalEndpoint: "tcuData",
  },

  {
    type: "Cell",
    title: "Battery Cells",
    fields: Array.from({ length: 128 }, (_, i) => ({
      key: `Cell${i + 1}`,
      label: `Cell ${i + 1}`,
      color: "#4CAF50",
    })),
    colors: ["#4CAF50"],
    hideLegend: true,
    dashboard: false,
    historicalEndpoint: "cellData",
  },
  {
    type: "Therm",
    title: "Thermistor Data",
    fields: [
      { key: "thermistor_id", label: "Thermistor ID", color: "#9C27B0" },
      { key: "therm1", label: "Therm 1", color: "#3F51B5" },
      { key: "therm2", label: "Therm 2", color: "#2196F3" },
      { key: "therm3", label: "Therm 3", color: "#4CAF50" },
    ],
    colors: ["#9C27B0", "#3F51B5", "#2196F3"],
    dashboard: false,
    historicalEndpoint: "thermData",
  },
  {
    type: "Bamocar",
    title: "Bamocar Controller",
    fields: [
      { key: "bamocar_frg", label: "FRG", color: "#9C27B0" },
      { key: "bamocar_rfe", label: "RFE", color: "#3F51B5" },
      { key: "brake_light", label: "Brake Light", color: "#F44336" },
    ],
    colors: ["#9C27B0", "#3F51B5", "#F44336"],
    unit: "RPM",
    dashboard: true,
    historicalEndpoint: "bamocarData",
  },
  {
    type: "BamocarTx",
    title: "Bamocar Tx Data",
    fields: [
      { key: "regid", label: "REGID", color: "#3F51B5" },
      { key: "data", label: "Data", color: "#FFC107" },
    ],
    colors: ["#3F51B5", "#FFC107"],
    dashboard: false,
    historicalEndpoint: "bamocarTxData",
  },
  {
    type: "BamoCarReTransmit",
    title: "Bamo Car Re-Transmit",
    fields: [
      { key: "motor_temp", label: "Motor Temp", color: "#FF5722" },
      { key: "controller_temp", label: "Controller Temp", color: "#9C27B0" },
    ],
    colors: ["#FF5722", "#9C27B0"],
    dashboard: false,
    historicalEndpoint: "bamoCarReTransmitData",
  },
  {
    type: "Encoder",
    title: "Encoder Data",
    fields: [
      { key: "encoder1", label: "Encoder 1", color: "#4CAF50" },
      { key: "encoder2", label: "Encoder 2", color: "#F44336" },
      { key: "encoder3", label: "Encoder 3", color: "#2196F3" },
      { key: "encoder4", label: "Encoder 4", color: "#FFC107" },
    ],
    colors: ["#4CAF50", "#F44336", "#2196F3", "#FFC107"],
    dashboard: false,
    historicalEndpoint: "encoderData",
  },
  {
    type: "PackCurrent",
    title: "Pack Current",
    fields: [{ key: "packcurrent", label: "Current", color: "#9C27B0" }],
    colors: ["#9C27B0"],
    unit: "A",
    dashboard: false,
    historicalEndpoint: "packCurrentData",
  },
  {
    type: "PackVoltage",
    title: "Pack Voltage",
    fields: [{ key: "packvoltage", label: "Voltage", color: "#3F51B5" }],
    colors: ["#3F51B5"],
    unit: "V",
    dashboard: false,
    historicalEndpoint: "packVoltageData",
  },
  {
    type: "PDMCurrent",
    title: "PDM Current",
    fields: [
      { key: "accumulator_current", label: "Accumulator", color: "#FF5722" },
      { key: "tcu_current", label: "TCU", color: "#3F51B5" },
      { key: "bamocar_current", label: "Bamocar", color: "#9C27B0" },
      { key: "pumps_current", label: "Pumps", color: "#4CAF50" },
      { key: "tsal_current", label: "TSAL", color: "#FFC107" },
      { key: "daq_current", label: "DAQ", color: "#00BCD4" },
      { key: "display_kvaser_current", label: "Display", color: "#8BC34A" },
      { key: "shutdown_reset_current", label: "Shutdown", color: "#E91E63" },
    ],
    colors: [
      "#FF5722",
      "#3F51B5",
      "#9C27B0",
      "#4CAF50",
      "#FFC107",
      "#00BCD4",
      "#8BC34A",
      "#E91E63",
    ],
    dashboard: false,
    historicalEndpoint: "pdmCurrentData",
  },
  {
    type: "PDMReTransmit",
    title: "PDM Re-Transmit",
    fields: [
      { key: "pdm_int_temperature", label: "Internal Temp", color: "#FF5722" },
      { key: "pdm_batt_voltage", label: "Batt Voltage", color: "#3F51B5" },
      { key: "global_error_flag", label: "Error Flag", color: "#F44336" },
      { key: "total_current", label: "Total Current", color: "#4CAF50" },
      { key: "internal_rail_voltage", label: "Rail Voltage", color: "#FFC107" },
      { key: "reset_source", label: "Reset Source", color: "#9C27B0" },
    ],
    colors: ["#FF5722", "#3F51B5", "#F44336", "#4CAF50", "#FFC107", "#9C27B0"],
    dashboard: false,
    historicalEndpoint: "pdmReTransmitData",
  },
  {
    type: "INSGPS",
    title: "INS GPS Data",
    fields: [
      { key: "gnss_week", label: "Week", color: "#9C27B0" },
      { key: "gnss_seconds", label: "Seconds", color: "#3F51B5" },
      { key: "gnss_lat", label: "Latitude", color: "#4CAF50" },
      { key: "gnss_long", label: "Longitude", color: "#FFC107" },
      { key: "gnss_height", label: "Height", color: "#F44336" },
    ],
    colors: ["#9C27B0", "#3F51B5", "#4CAF50", "#FFC107", "#F44336"],
    dashboard: false,
    historicalEndpoint: "insGPSData",
  },
  {
    type: "INSIMU",
    title: "INS IMU Data",
    fields: [
      { key: "north_vel", label: "North Velocity", color: "#4CAF50" },
      { key: "east_vel", label: "East Velocity", color: "#F44336" },
      { key: "up_vel", label: "Up Velocity", color: "#2196F3" },
      { key: "roll", label: "Roll", color: "#FFC107" },
      { key: "pitch", label: "Pitch", color: "#9C27B0" },
      { key: "azimuth", label: "Azimuth", color: "#3F51B5" },
      { key: "status", label: "Status", color: "#E91E63" },
    ],
    colors: [
      "#4CAF50",
      "#F44336",
      "#2196F3",
      "#FFC107",
      "#9C27B0",
      "#3F51B5",
      "#E91E63",
    ],
    dashboard: false,
    historicalEndpoint: "insIMUData",
  },
  {
    type: "FrontFrequency",
    title: "Front Frequency Data",
    fields: [
      { key: "rear_right", label: "Rear Right", color: "#4CAF50" },
      { key: "front_right", label: "Front Right", color: "#F44336" },
      { key: "rear_left", label: "Rear Left", color: "#2196F3" },
      { key: "front_left", label: "Front Left", color: "#FFC107" },
    ],
    colors: ["#4CAF50", "#F44336", "#2196F3", "#FFC107"],
    dashboard: false,
    historicalEndpoint: "frontFrequencyData",
  },
  {
    type: "FrontStrainGauges1",
    title: "Front Strain Gauges 1",
    fields: [
      { key: "gauge1", label: "Gauge 1", color: "#9C27B0" },
      { key: "gauge2", label: "Gauge 2", color: "#3F51B5" },
      { key: "gauge3", label: "Gauge 3", color: "#4CAF50" },
      { key: "gauge4", label: "Gauge 4", color: "#FFC107" },
      { key: "gauge5", label: "Gauge 5", color: "#F44336" },
      { key: "gauge6", label: "Gauge 6", color: "#00BCD4" },
    ],
    colors: ["#9C27B0", "#3F51B5", "#4CAF50", "#FFC107", "#F44336", "#00BCD4"],
    dashboard: false,
    historicalEndpoint: "frontStrainGauges1Data",
  },
  {
    type: "FrontStrainGauges2",
    title: "Front Strain Gauges 2",
    fields: [
      { key: "gauge1", label: "Gauge 1", color: "#9C27B0" },
      { key: "gauge2", label: "Gauge 2", color: "#3F51B5" },
      { key: "gauge3", label: "Gauge 3", color: "#4CAF50" },
      { key: "gauge4", label: "Gauge 4", color: "#FFC107" },
      { key: "gauge5", label: "Gauge 5", color: "#F44336" },
      { key: "gauge6", label: "Gauge 6", color: "#00BCD4" },
    ],
    colors: ["#9C27B0", "#3F51B5", "#4CAF50", "#FFC107", "#F44336", "#00BCD4"],
    dashboard: false,
    historicalEndpoint: "frontStrainGauges2Data",
  },
  {
    type: "FrontAnalog",
    title: "Front Analog Data",
    fields: [
      { key: "left_rad", label: "Left Rad", color: "#4CAF50" },
      { key: "right_rad", label: "Right Rad", color: "#F44336" },
      { key: "front_right_pot", label: "Front Right Pot", color: "#2196F3" },
      { key: "front_left_pot", label: "Front Left Pot", color: "#FFC107" },
      { key: "rear_right_pot", label: "Rear Right Pot", color: "#9C27B0" },
      { key: "rear_left_pot", label: "Rear Left Pot", color: "#3F51B5" },
      { key: "steering_angle", label: "Steering Angle", color: "#E91E63" },
      { key: "analog8", label: "Analog8", color: "#00BCD4" },
    ],
    colors: [
      "#4CAF50",
      "#F44336",
      "#2196F3",
      "#FFC107",
      "#9C27B0",
      "#3F51B5",
      "#E91E63",
      "#00BCD4",
    ],
    dashboard: false,
    historicalEndpoint: "frontAnalogData",
  },
  {
    type: "ACULVFD1",
    title: "ACULV FD 1 Data",
    fields: [
      { key: "ams_status", label: "AMS Status", color: "#9C27B0" },
      { key: "fld", label: "FLD", color: "#3F51B5" },
      { key: "state_of_charge", label: "State of Charge", color: "#4CAF50" },
      {
        key: "accumulator_voltage",
        label: "Accumulator Voltage",
        color: "#FFC107",
      },
      { key: "tractive_voltage", label: "Tractive Voltage", color: "#F44336" },
      { key: "cell_current", label: "Cell Current", color: "#00BCD4" },
      {
        key: "isolation_monitoring",
        label: "Isolation Monitoring",
        color: "#8BC34A",
      },
      {
        key: "isolation_monitoring1",
        label: "Isolation Monitoring 1",
        color: "#E91E63",
      },
    ],
    colors: [
      "#9C27B0",
      "#3F51B5",
      "#4CAF50",
      "#FFC107",
      "#F44336",
      "#00BCD4",
      "#8BC34A",
      "#E91E63",
    ],
    dashboard: false,
    historicalEndpoint: "aculvFd1Data",
  },
];
